Filminurk/Filminurk/Models/AccuWeather/AccuWeatherSearchViewModel.cs
namespace Filminurk.Models.AccuWeather
{
    public class AccuWeatherSearchViewModel
    {
        public string CityName { get; set; } = string.Empty;
    }
}

Filminurk/Filminurk/Controllers/AccuWeatherController.cs
using Filminurk.Core.ServiceInterface;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class AccuWeatherController : Controller
    {
        private readonly IWeatherForecastServices _weatherForecastServices;
        public AccuWeatherController(IWeatherForecastServices weatherForecastServices)
        {
            _weatherForecastServices = weatherForecastServices;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Filminurk/Filminurk/Views/AccuWeather/Index.cshtml
@model Filminurk.Models.AccuWeather.AccuWeatherSearchViewModel

<h1>Otsi linna ilma</h1>

<div class="container">
	<form method="post">
		<div class="container">
			<div class="form-group col-md-offset-3 col-md-5">
				<h2>Siit saad ilma otsida soovitud linnast:</h2>
				<label for="CityName" style="font:Arial"></label>
				<input asp-for="CityName" class="form-control"/>
				<span asp-validation-for="CityName" class="text-danger"></span>
			</div>
		</div>
	
		<div class="container">
			<div class="form-group col-md-offset-3 col-md-5">
				<button asp-controller="AccuWeather" asp-action="FindWeather" class="btn btn-primary">Otsi</button>
			</div>
		</div>
	
	</form>
</div>