Filminurk/Filminurk/Models/FavouriteLists/FavouriteListsAdminCreateEditViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListsAdminCreateEditViewModel
    {
        public Guid FavouriteListID { get; set; }
        public string ListBelongsToUser { get; set; }
        public bool IsMovieOrActor { get; set; } // true = Movie, false = Actor
        public string ListName { get; set; }
        public string ListDescription { get; set; }
        public bool IsPrivate { get; set; }
        public List<Movie> ListOfMovies { get; set; }
        //public List<Actor>? ListOfActors { get; set; }

        /* andmebaasiomadused */
        public DateTime? ListCreatedAt { get; set; }
        public DateTime? ListModifiedAt { get; set; }
        public DateTime? ListDeletedAt { get; set; }
        public bool? IsReported { get; set; } = false;
        // imagemodel for index
        public List<FavouriteListsIndexImageViewModel> Image { get; set; } = new List<FavouriteListsIndexImageViewModel>();
    }
}

Filminurk/Filminurk/Models/FavouriteLists/FavouriteListsIndexImageViewModel.cs
namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListsIndexImageViewModel
    {
        public Guid ImageID { get; set; }
        public string ImageTitle { get; set; }
        public byte[] ImageData { get; set; }
        public string Image { get; set; }
        public Guid? ListID { get; set; }
    }
}

Filminurk/Filminurk/Models/FavouriteLists/FavouriteListsIndexViewModel.cs
using Filminurk.Core.Domain;
using Filminurk.Models.Movies;

namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListsIndexViewModel
    {
        public Guid FavouriteListID { get; set; }
        public string ListBelongsToUser { get; set; }
        public bool IsMovieOrActor { get; set; } // true = Movie, false = Actor
        public string ListName { get; set; }
        public string? ListDescription { get; set; }
        public bool? IsPrivate { get; set; }
        //public List<Movie>? ListOfMovies { get; set; }
        //public List<Actor>? ListOfActors { get; set; }

        /* andmebaasiomadused */
        public DateTime? ListCreatedAt { get; set; }
        public DateTime? ListModifiedAt { get; set; }
        public DateTime? ListDeletedAt { get; set; }
        public bool? IsReported { get; set; } = false;
        // imagemodel for index
        public List<FavouriteListsIndexImageViewModel> Image { get; set; } = new List<FavouriteListsIndexImageViewModel>();
    }
}

Filminurk/Filminurk/Models/FavouriteLists/FavouriteListsUserCreateViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListsUserCreateViewModel
    {
        public Guid FavouriteListID { get; set; }
        public string ListBelongsToUser { get; set; }
        public bool IsMovieOrActor { get; set; } // true = Movie, false = Actor
        public string ListName { get; set; }
        public string ListDescription { get; set; }
        public bool IsPrivate { get; set; }
        public List<Movie> ListOfMovies { get; set; }
        //public List<Actor>? ListOfActors { get; set; }

        /* andmebaasiomadused */
        public DateTime? ListCreatedAt { get; set; }
        public DateTime? ListModifiedAt { get; set; }
        public DateTime? ListDeletedAt { get; set; }
        public bool? IsReported { get; set; } = false;
        // imagemodel for index
        public List<FavouriteListsIndexImageViewModel> Image { get; set; } = new List<FavouriteListsIndexImageViewModel>();
    }
}

Filminurk/Filminurk/Models/FavouriteLists/FavouriteListsUserDetailsViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListsUserDetailsViewModel
    {
        public Guid FavouriteListID { get; set; }
        public string ListBelongsToUser { get; set; }
        public bool IsMovieOrActor { get; set; } // true = Movie, false = Actor
        public string ListName { get; set; }
        public string ListDescription { get; set; }
        public bool IsPrivate { get; set; }
        public List<Movie> ListOfMovies { get; set; }
        //public List<Actor>? ListOfActors { get; set; }

        /* andmebaasiomadused */
        public DateTime? ListCreatedAt { get; set; }
        public DateTime? ListModifiedAt { get; set; }
        public DateTime? ListDeletedAt { get; set; }
        public bool? IsReported { get; set; } = false;
        // imagemodel for index
        // public FavouriteListsIndexImageViewModel Image { get; set; } = new FavouriteListsIndexImageViewModel();
    }
}

Filminurk/Filminurk/Controllers/FavouriteListsController.cs
using Filminurk.Core.Domain;
using Filminurk.Core.Dto;
using Filminurk.Core.ServiceInterface;
using Filminurk.Data;
using Filminurk.Models.FavouriteLists;
using Filminurk.Models.Movies;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class FavouriteListsController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        private readonly IFavouriteListsServices _FavouriteListsServices;
        //fileService missing
        public FavouriteListsController(FilminurkTARpe24Context context, IFavouriteListsServices favouriteListsServices)
        {
            _context = context;
            _FavouriteListsServices = favouriteListsServices;
        }
        public IActionResult Index()
        {
            var resultingLists = _context.FavouriteLists
                .OrderByDescending(y => y.ListCreatedAt) /* sorteeri nimekiri langevas järjekorras loodud kuupäeva järgi */
                .Select(x => new FavouriteListsIndexViewModel
                {
                    FavouriteListID = x.FavouriteListID,
                    ListBelongsToUser = x.ListBelongsToUser,
                    IsMovieOrActor = x.IsMovieOrActor,
                    ListName = x.ListName,
                    ListDescription = x.ListDescription,
                    ListCreatedAt = x.ListCreatedAt,
                    ListDeletedAt = (DateTime)x.ListDeletedAt,
                    Image = (List<FavouriteListsIndexImageViewModel>)_context.FilesToDatabase
                        .Where(ml => ml.ListID == x.FavouriteListID)
                        .Select(li => new FavouriteListsIndexImageViewModel
                        {
                            ListID = li.ListID,
                            ImageID = li.ImageID,
                            ImageData = li.ImageData,
                            ImageTitle = li.ImageTitle,
                            Image = string.Format("data:image/gif;base64,{0}",
                            Convert.ToBase64String(li.ImageData)),
                        })

                });
            return View(resultingLists);
        }

        [HttpGet]
        public IActionResult UserCreate()
        {
            var movies = _context.Movies
                .OrderBy(m => m.Title)
                .Select(mo => new MoviesIndexViewModel
                {
                    Id = mo.Id,
                    Title = mo.Title,
                    FirstPublished = mo.FirstPublished,
                    Genre = mo.Genre,
                })
                .ToList();
            ViewData["allmovies"] = movies;
            ViewData["UserHasSelected"] = new List<string>();

            // this is for normal user
            FavouriteListsUserCreateViewModel vm = new();
            return View("UserCreate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> UserCreate(FavouriteListsUserCreateViewModel vm, List<string> userHasSelected,
            List<MoviesIndexViewModel> movies)
        {
            List<Guid> tempParse = new();
            foreach (var stringID in userHasSelected)
            {
                tempParse.Add(Guid.Parse(stringID));
            }

            var newListDto = new FavouriteListDTO() { };
            newListDto.ListName = vm.ListName;
            newListDto.ListDescription = vm.ListDescription;
            newListDto.IsMovieOrActor = vm.IsMovieOrActor;
            newListDto.IsPrivate = vm.IsPrivate;
            newListDto.ListCreatedAt = DateTime.UtcNow;
            newListDto.ListBelongsToUser = "00000000-0000-0000-0000-000000000001";
            newListDto.ListModifiedAt = DateTime.UtcNow;
            newListDto.ListDeletedAt = vm.ListDeletedAt;

            var listofmoviestoadd = new List<Movie>();
            foreach (var movieId in tempParse)
            {
                Movie thismovie = (Movie)_context.Movies.Where(m => m.Id == movieId).ToList().First();
                listofmoviestoadd.Add(thismovie);

            }
            newListDto.ListOfMovies = listofmoviestoadd;

            List<Guid> convertedIDs = new List<Guid>();
            if (newListDto.ListOfMovies != null)
            {
                convertedIDs = MovieToId(newListDto.ListOfMovies);
            }
            var newList = await _FavouriteListsServices.Create(newListDto /*, convertedIDs*/);
            if (newList == null)
            {
                return BadRequest();
            }
            return RedirectToAction("Index", vm);
        }

        [HttpGet]
        public async Task<IActionResult> UserDetails(Guid id, Guid thisuserid)
        {
            if (id == null || thisuserid == null)
            {
                return BadRequest();
                //TODO: return corresponding errorviews. id not found for list, and user login error for userid
            }
            var thisList = _context.FavouriteLists
                .Where(tl => tl.FavouriteListID == id && tl.ListBelongsToUser == thisuserid.ToString())
                .Select(
                stl => new FavouriteListsUserDetailsViewModel
                {
                    FavouriteListID = stl.FavouriteListID,
                    ListBelongsToUser = stl.ListBelongsToUser,
                    IsMovieOrActor = stl.IsMovieOrActor,
                    ListName = stl.ListName,
                    ListDescription = stl.ListDescription,
                    IsPrivate = stl.IsPrivate,
                    ListOfMovies = stl.ListOfMovies,
                    IsReported = stl.IsReported,
                    //Image = _context.FilesToDatabase
                    //.Where(i => i.ListID == stl.FavouriteListID)
                    //.Select(si => new FavouriteListsIndexImageViewModel
                    //{
                    //    ImageID = si.ImageID,
                    //    ListID = si.ListID,
                    //    ImageData = si.ImageData,
                    //    ImageTitle = si.ImageTitle,
                    //    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(si.ImageData))
                    //}).ToList()
                }).First();
            //add viewdata attribute here later, to discern between user and admin
            if (thisList == null)
            {
                return NotFound();
            }
            return View("Details", thisList);
        }

        [HttpPost]
        public async Task<IActionResult> UserTogglePrivacy(Guid id)
        {
            FavouriteList thisList = await _FavouriteListsServices.DetailsAsync(id);

            FavouriteListDTO updatedList = new FavouriteListDTO();
            updatedList.FavouriteListID = thisList.FavouriteListID;
            updatedList.ListBelongsToUser = thisList.ListBelongsToUser;
            updatedList.ListName = thisList.ListName;
            updatedList.ListDescription = thisList.ListDescription;
            updatedList.IsPrivate = thisList.IsPrivate;
            updatedList.ListOfMovies = thisList.ListOfMovies;
            updatedList.IsReported = thisList.IsReported;
            updatedList.IsMovieOrActor = thisList.IsMovieOrActor;
            updatedList.ListCreatedAt = thisList.ListCreatedAt;
            updatedList.ListModifiedAt = DateTime.UtcNow;
            updatedList.ListDeletedAt = thisList.ListDeletedAt;
            ViewData["UpdateServiceType"] = "Private";

            thisList.IsPrivate = !updatedList.IsPrivate;

            var result = await _FavouriteListsServices.Update(updatedList, "Private");
            if (result == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> UserDelete(Guid id) 
        { 
            var deletedList = await _FavouriteListsServices.DetailsAsync(id);
            deletedList.ListDeletedAt = DateTime.Now;

            var dto = new FavouriteListDTO();
            dto.FavouriteListID = deletedList.FavouriteListID;
            dto.ListBelongsToUser = deletedList.ListBelongsToUser;
            dto.ListName = deletedList.ListName;
            dto.ListDescription = deletedList.ListDescription;
            dto.IsPrivate = deletedList.IsPrivate;
            dto.ListOfMovies = deletedList.ListOfMovies;
            dto.IsReported = deletedList.IsReported;
            dto.IsMovieOrActor = deletedList.IsMovieOrActor;
            dto.ListCreatedAt = deletedList.ListCreatedAt;
            dto.ListModifiedAt = DateTime.Now;
            dto.ListDeletedAt = deletedList.ListDeletedAt;
            ViewData["UpdateServiceType"] = "Delete";
            
            var result = await _FavouriteListsServices.Update(dto, "Delete");
            if (result == null) 
            { 
                NotFound();
            }

            return RedirectToAction("Index");
        }

        private List<Guid> MovieToId(List<Movie> listOfMovies)
        {
            var result = new List<Guid>();
            foreach (var movie in listOfMovies)
            {
                result.Add(movie.Id);
            }
            return result;
        }
    }
}

Filminurk/Filminurk/Views/FavouriteLists/Details.cshtml
@model Filminurk.Models.FavouriteLists.FavouriteListsUserDetailsViewModel
@{
	int rowNumber = 1;
}

<div>
	@if (Model.IsReported == true)
	{
		@:Sinu nimekiri rikub kogukonna reegleid<br/>
		@:Oleme seadnud nimekirja privaatseks kuni admin selle üle vaatab.<br/>
	}
	<table>
		<tr><h1>@Model.ListName</h1></tr>
		<tr>@*<partial name="_imageIndex" model="@Model.Image"></partial>*@IMAGE HERE</tr>
		<tr>@Model.IsPrivate.ToString()</tr>
	</table>
</div>

<div>
	<form method="post">
	<table class="table">
		@foreach (var movie in Model.ListOfMovies)
		{
			<tr>
				<table class="table" style="border:thick;">
					<tr>
						<td colspan="2">@movie.Title</td>
					</tr>
					<tr>
						<td>(IMAGE HERE)</td>
						<td>
							<table>
								<tr>@movie.Description</tr>
								<tr>@movie.Director</tr>
								<tr>@movie.Language</tr>
								<tr>@movie.CurrentRating</tr>
								<tr>@movie.Genre</tr>
							</table>
						</td>
					</tr>
				</table>
			</tr>
		}
	</table>
	<div>
		<input asp-action="UserDelete" asp-controller="FavouriteLists" asp-route-id="@Model.FavouriteListID"
			type="submit" class="btn btn-danger" value="Kustuta Nimekiri"/>
		<input asp-action="UserTogglePrivacy" asp-controller="FavouriteLists" asp-route-id="@Model.FavouriteListID"
			type="submit" class="btn btn-warning" value="Muuda Nimekiri privaatseks" />
		<input asp-action="UserEditList" asp-controller="FavouriteLists" asp-route-id="@Model.FavouriteListID"
			   type="submit" class="btn btn-success" value="Muuda Nimekirja sisu ja andmeid" />
		<a asp-action="Index" asp-controller="FavouriteLists" class="btn btn-light">Tagasi</a>
	</div>
	</form>
</div>

Filminurk/Filminurk/Views/FavouriteLists/Index.cshtml
@model IEnumerable<Filminurk.Models.FavouriteLists.FavouriteListsIndexViewModel>

@{
	int rowNumber = 1;
	int currentRow = 1;
	int currentTile = 1;
	int tilesInRow = 1;
}
<div>
	<a asp-action="UserCreate" asp-controller="FavouriteLists" class="btn btn-primary">Tee uus lemmikute nimekiri</a>
	<a asp-action="Index" asp-controller="Home" class="btn btn-primary">Pealeht</a>
</div>
<div @* no class currently, no design specified*@>
	<form method="post">
		<table class="table">
			<thead>
				@if (!Model.Any())
				{
					<tr>
						<th scope="col" colspan="2">
							<span>kahjuks ei leidnud ühtegi lemmikute nimekirja.</span>
						</th>
					</tr>
				}
				else
				{
					<tr>
						<th scope="col" colspan="2">
							<span>Sinu nimekirjad:</span>
						</th>
					</tr>
				}
			</thead>
			<tbody>
				@if (!Model.Any())
				{
					<table>
						<tr>
							<td colspan="2">Sorry, no list</td>
						</tr>
						<tr>
							<td><img width="128" src="~/lib/defaultassets/image/noposter.png"/></td>
						</tr>
					</table>
				}
				else
				{
					@foreach (var list in Model)
					{
						if (list.ListDeletedAt == null)
						{
							<table>
								<tr>
									<td colspan="2">

										<a asp-action="UserDetails" asp-controller="FavouriteLists" asp-route-id="@list.FavouriteListID"
										   asp-route-thisuserid="@list.ListBelongsToUser">@list.ListName</a>
								</tr>
								<tr>
									<td>
										@foreach (var image in list.Image)
										{
											<partial name="_ImageIndex" model="image" />
										}
										<img width="128" src="~/lib/defaultassets/image/noposter.png" />
									</td>
									<td>@list.ListDescription</td>
								</tr>
							</table>
						}
					}
					rowNumber++;
				}
			</tbody>
		</table>
	</form>
</div>

Filminurk/Filminurk/Views/FavouriteLists/UserCreate.cshtml
@model Filminurk.Models.FavouriteLists.FavouriteListsUserCreateViewModel
@* check for editing or creating *@
@{
	var allMoviesTickboxes = ViewData["allmovies"] as List<Filminurk.Models.Movies.MoviesIndexViewModel>;
	List<string> userHasSelected = ViewBag.userHasSelected;
	List<string> previouslySelected = userHasSelected;
}
<h1>Tee uus nimekiri</h1>

<div>
	<form method="post" enctype="multipart/form-data">
		<input asp-for="FavouriteListID" type="hidden"/>
		<input asp-for="ListCreatedAt" type="hidden"/>
		<input asp-for="ListModifiedAt" type="hidden"/>
		<input asp-for="ListDeletedAt" type="hidden"/>
		<input asp-for="IsReported" type="hidden"/>
		<input asp-for="ListBelongsToUser" type="hidden"/>

		<div class="form-group-row">
			<label asp-for="ListName" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="ListName" class="form-control"/>
			</div>
		</div>

		<div class="form-group-row">
			<label asp-for="ListDescription" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="ListDescription" class="form-control" />
			</div>
		</div>

		<div class="form-group-row">
			<label asp-for="IsPrivate" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input type="checkbox" asp-for="IsPrivate" class="form-control" />
			</div>
		</div>

		@if (allMoviesTickboxes == null)
		{
			<tr>Filme andmebaasis ei ole</tr>
		}
		else
		{
			foreach (var movie in ViewBag.allmovies)
			{
				<tr>
					<td>movie.Title</td>
					<td>movie.FirstPublished</td>
					<td>movie.MovieGenre</td>
					<td>
						@if(movie.ID.HasValue)
						{
							<input type="checkbox" name="userHasSelected" value="@movie.ID" id="checkbox-@movie.ID" 
							@if (userHasSelected.Contains(movie.ID.ToString()))
							{
								@:checked
							}
							/>
						}
						else
						{
							<input type="checkbox" name="userHasSelected" value="@movie.ID" id="checkbox-@movie.ID"/>
						}
					</td>
				</tr>
			}
		}

		<input asp-action="UserCreate" asp-controller="FavouriteLists" type="submit" class="btn btn-primary" value="Tee nimekiri"/>
		
	</form>
</div>

Filminurk/Filminurk/Views/FavouriteLists/_ImageIndex.cshtml
@model Filminurk.Models.FavouriteLists.FavouriteListsIndexImageViewModel
<div>
	@if (!Model.Image.Any())
	{
		<p>Pilte pole</p>	
	}
</div>
@if (Model.ImageTitle == "Poster")
{
	<img class="card-img-top" src="@Model.Image" asp-append-version="true"/>
}
else
{
	<img width="128" src="~/lib/defaultassets/image/noposter.png"/>
}